include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    use_build_context_synchronously: ignore
    avoid_print: ignore
    no_leading_underscores_for_local_identifiers: ignore
    library_private_types_in_public_api: ignore
