name: dine_deals
description: "Experience new dining deals everyday"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  apple_maps_flutter: ^1.4.0
  flutter:
    sdk: flutter
  flutter_map: ^8.1.0
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  supabase_flutter: ^2.0.0
  timeago: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
