name: dine_deals
description: "Experience new dining deals everyday"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  apple_maps_flutter: ^1.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_map: ^8.1.0
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  geolocator: ^13.0.4
  google_fonts: ^6.2.1
  http: ^1.3.0
  image_picker: ^1.0.4
  latlong2: ^0.9.1
  permission_handler: ^11.4.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.8.4
  timeago: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.otf
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.otf
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYBOLD.otf
          weight: 700
