name: TestFlight Deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Create .env from secrets
        run: |
          echo "OPENCAGE_API=${{ secrets.OPENCAGE_API }}" > .env
          echo "OPENCAGE_URL=${{ secrets.OPENCAGE_URL }}" >> .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env

      - name: Setup iOS certificates and provisioning
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.IOS_CERTIFICATE_P12 }}
          p12-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}

      - name: Build iOS with code signing
        run: |
          flutter build ios --release
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -archivePath Runner.xcarchive archive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath Runner.xcarchive -exportPath ../build/ios/ipa -exportOptionsPlist exportOptions.plist

      - name: Build and upload to TestFlight
        uses: Apple-Actions/upload-testflight-build@v1
        with:
          app-path: "build/ios/ipa/Runner.ipa"
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
